### ISSUE TITLE
getUrl

### ISSUE THREAD

**Issue by ADroidCoder** [EthanOrange/wechat-redirect#1]
我想问下 http://144.34.193.163:3000/api/geturl?url=这个接口返回的data字段的内容e52985a0是干嘛用的？？

**Comment by 3lang3** [comment]
@ADroidCoder
返回的是对应你服务器redis存储键值对的key，这个key对应的就是需要跳转的url
用户通过访问/jump/e52985a0这个路由 我们就能判断用户环境 进行跳出微信浏览器操作

**Comment by 3lang3** [comment]
@ADroidCoder
为什么返回短码（破产版短码）
为了把需要跳转的url伪装起来，精简长度，不然一个下载apk的url可能长出天际

**Comment by ADroidCoder** [comment]
感谢解答
