### ISSUE TITLE
[root@VM_0_3_centos wechat-redirect]# nginx -c /home/wwwroot/default/wechat-redirect/nginx.conf  nginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) in /home/wwwroot/default/wechat-redirect/nginx.conf:23

### ISSUE THREAD

**Issue by fashionwill** [EthanOrange/wechat-redirect#10]
[root@VM_0_3_centos wechat-redirect]# nginx -c /home/wwwroot/default/wechat-redirect/nginx.conf 
nginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) in /home/wwwroot/default/wechat-redirect/nginx.conf:23

最后一步失败了

**Comment by fashionwill** [comment]
docker run wechatredirect_web_1
Unable to find image 'wechatredirect_web_1:latest' locally
Trying to pull repository docker.io/library/wechatredirect_web_1 ... 
/usr/bin/docker-current: repository docker.io/wechatredirect_web_1 not found: does not exist or no pull access.

镜像好像不在了

**Comment by 3lang3** [comment]
第一个是nginx配置报错 找不到MIME.types 这个需要按需配置
第二个 镜像需要本地构建dockerhub本身就没发布 应该是你构建失败了
