### ISSUE TITLE
部署启动nginx出错

### ISSUE THREAD

**Issue by pytian** [EthanOrange/wechat-redirect#11]
nginx -c 项目根目录/nginx.conf

bogon:wechat-redirect tian$ nginx -c wechat-redirect/nginx.conf
nginx: [emerg] open() "/usr/local/Cellar/nginx/1.17.3_1/wechat-redirect/nginx.conf" failed (2: No such file or directory)

项目根目录不是项目名吗

**Comment by 3lang3** [comment]
@pytian 
```shell
# 项目绝对路径 /home/www/wechat-redirect
nginx -c /home/www/wechat-redirect/nginx.conf
```
nginx.conf 文件一般需要按需配置下的, 比如第23行的include 
```nginx
 include /etc/nginx/mime.types;
```
一般可以参考系统自带的nginx.conf.default 进行调整
