### ISSUE TITLE
BrowserslistError

### ISSUE THREAD

**Issue by EricFung** [EthanOrange/wechat-redirect#3]
BrowserslistError:Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.
example/front :npm run build 运行时会报错，刚去Browserslist官方看了眼，issues列表全是这个报错了。。。有没有替代方案呢。还是等作者修复这个问题

**Comment by 3lang3** [comment]
@EricFung 刚看到issue 抱歉
刚跑了一遍确认没有问题
platform: macOs Mojave
node v11.3.0
npm v6.9.0

**Comment by 3lang3** [comment]
> Unknown browser query android all

@EricFung 
[https://github.com/facebook/create-react-app/issues/7239](https://github.com/facebook/create-react-app/issues/7239)
有关于此issue的讨论

**Comment by EricFung** [comment]
我想还是关掉这个问题吧。好像他们已经解决掉这个问题了。
对当前这个项目是没啥影响了
