### ISSUE TITLE
部署demo出现问题

### ISSUE THREAD

**Issue by pliybird** [EthanOrange/wechat-redirect#8]
使用docker部署的，但一直跑不起来
![image](https://user-images.githubusercontent.com/13210622/61778869-2989b800-ae32-11e9-8630-d298550f0fd9.png)

**Comment by 3lang3** [comment]
@pliybird  看着像npm install到时候出了问题 
你本机部署成功了吗？

**Comment by gossterrible** [comment]
@pliybird @EthanOrange Did anyone figure out a solution? I'm facing the same issue when executing `npm run docker`

```
node ver : v10.16.0
npm ver: 6.9.0
```

**Comment by 3lang3** [comment]
@gossterrible 
what's your platform?

**Comment by pliybird** [comment]
> @pliybird 看着像npm install到时候出了问题
> 你本机部署成功了吗？

@EthanOrange 本机没有部署成功，我手动 `npm install` 也不行，会不会是Dockerfile的问题呢

本地环境
↓↓↓↓↓↓↓
```
platform :  Mac OS X
node version : v11.3.0
npm version : 6.4.1
```

**Comment by 3lang3** [comment]
@pliybird 你先非docker部署下试试 看能不能成功 
我直接 docker-compose up 是能运行的 
这个dockerfile没什么特殊的地方 你尝试根据实际情况修改下？

**Comment by pliybird** [comment]
> @pliybird 你先非docker部署下试试 看能不能成功
> 我直接 docker-compose up 是能运行的
> 这个dockerfile没什么特殊的地方 你尝试根据实际情况修改下？

@EthanOrange 今天重新测试了下，Dockerfile 没问题，直接在根目录`npm run docker`一键部署成功，另外我非docker安装也是一次性成功的，感谢作者
